(() => {
'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let sb, actions=[];
const result=(t,type='success')=>{const e=$('acoes-admin-result');if(e){e.textContent=t;e.className=`admin-result ${type}`;e.hidden=false;}};
async function xlsx(){if(window.XLSX)return window.XLSX;await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)});return window.XLSX}
const date=v=>v?new Date(v).toLocaleDateString('pt-PT'):'—', dt=v=>v?new Date(v).toLocaleString('pt-PT'):'—';
function form(a={}){return `<form id="acao-form" class="acao-form-grid"><input type="hidden" id="acao-id" value="${esc(a.id||'')}"><label>Título<input id="acao-titulo" required value="${esc(a.titulo||'')}"></label><label>Local<input id="acao-local" value="${esc(a.local||'')}"></label><label>Data<input id="acao-data" type="date" value="${esc(a.data||'')}"></label><label>Hora<input id="acao-hora" type="time" value="${esc(String(a.hora||'').slice(0,5))}"></label><label>Prazo de inscrição<input id="acao-prazo" type="datetime-local" value="${a.prazo_inscricao?new Date(a.prazo_inscricao).toISOString().slice(0,16):''}"></label><label>Limite de inscrições<input id="acao-limite" type="number" min="1" value="${esc(a.limite_inscricoes??'')}"></label><label>Valor (€)<input id="acao-valor" type="number" min="0" step="0.01" value="${esc(a.valor??0)}"></label><div class="acao-checks"><label class="acao-check"><input id="acao-ativa" type="checkbox" ${a.ativa?'checked':''}> Ação ativa</label><label class="acao-check"><input id="acao-aberta" type="checkbox" ${a.inscricoes_abertas?'checked':''}> Inscrições abertas</label><label class="acao-check"><input id="acao-pagamento" type="checkbox" ${a.pagamento_obrigatorio?'checked':''}> Pagamento obrigatório</label><label class="acao-check"><input id="acao-comprovativo" type="checkbox" ${a.comprovativo_obrigatorio?'checked':''}> Comprovativo obrigatório</label></div><label class="wide">Descrição<textarea id="acao-descricao">${esc(a.descricao||'')}</textarea></label><div class="acao-admin-actions wide"><button class="admin-small-btn primary" type="submit">${a.id?'Guardar alterações':'Criar ação'}</button>${a.id?'<button class="admin-small-btn" id="acao-cancel" type="button">Cancelar</button>':''}</div></form>`}
async function load(){const r=await sb.from('acoes').select('*').order('created_at',{ascending:false});if(r.error)throw r.error;actions=r.data||[];render()}
function render(){const root=$('acoes-admin-list');root.innerHTML=actions.length?actions.map(a=>`<article class="acao-admin-card"><div class="acao-card-head"><div><h3>${esc(a.titulo)}</h3><div class="acao-meta"><span>📅 ${date(a.data)}</span>${a.hora?`<span>🕐 ${esc(String(a.hora).slice(0,5))}</span>`:''}${a.local?`<span>📍 ${esc(a.local)}</span>`:''}<span>${a.pagamento_obrigatorio?`💶 ${Number(a.valor||0).toFixed(2).replace('.',',')} €`:'💶 Sem pagamento'}</span></div></div><div class="acao-badges"><span class="acao-badge ${a.ativa?'ok':''}">${a.ativa?'Ativa':'Inativa'}</span><span class="acao-badge ${a.inscricoes_abertas?'ok':''}">${a.inscricoes_abertas?'Inscrições abertas':'Fechadas'}</span>${a.comprovativo_obrigatorio?'<span class="acao-badge warn">Comprovativo obrigatório</span>':''}</div></div><p class="acao-description">${esc(a.descricao||'Sem descrição.')}</p><div class="acao-admin-actions"><button class="admin-small-btn primary" data-edit="${a.id}">Editar</button><button class="admin-small-btn" data-list="${a.id}">Ver inscritos</button><button class="admin-small-btn" data-export="${a.id}">Exportar Excel</button></div><div id="regs-${a.id}" class="acao-inscricoes-table-wrap" hidden></div></article>`).join(''):'<div class="acao-empty">Ainda não existem ações.</div>';
root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const a=actions.find(x=>x.id===b.dataset.edit);$('acoes-admin-form-wrap').innerHTML=form(a);bindForm()});
root.querySelectorAll('[data-list]').forEach(b=>b.onclick=()=>listRegs(b.dataset.list));root.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportRegs(b.dataset.export));}
function bindForm(){const f=$('acao-form');if(!f||f.dataset.bound)return;f.dataset.bound=1;$('acao-cancel')?.addEventListener('click',()=>{$('acoes-admin-form-wrap').innerHTML=form();bindForm()});f.onsubmit=async e=>{e.preventDefault();try{const payment=$('acao-pagamento').checked,proof=$('acao-comprovativo').checked;if(proof&&!payment)throw Error('O comprovativo só pode ser obrigatório com pagamento.');const p={titulo:$('acao-titulo').value.trim(),descricao:$('acao-descricao').value.trim()||null,data:$('acao-data').value||null,hora:$('acao-hora').value||null,local:$('acao-local').value.trim()||null,prazo_inscricao:$('acao-prazo').value?new Date($('acao-prazo').value).toISOString():null,limite_inscricoes:$('acao-limite').value?Number($('acao-limite').value):null,ativa:$('acao-ativa').checked,inscricoes_abertas:$('acao-aberta').checked,pagamento_obrigatorio:payment,valor:payment?Number($('acao-valor').value||0):0,comprovativo_obrigatorio:payment&&proof};if(!p.titulo)throw Error('Indica o título.');const id=$('acao-id').value;const r=id?await sb.from('acoes').update(p).eq('id',id):await sb.from('acoes').insert(p);if(r.error)throw r.error;result(id?'Ação atualizada.':'Ação criada.');$('acoes-admin-form-wrap').innerHTML=form();bindForm();await load()}catch(e){result(e.message||String(e),'error')}}}
async function regs(id){let q=sb.from('acoes_inscricoes').select('id,acao_id,socio_id,data_inscricao,estado,pagamento_confirmado,comprovativo_path,comprovativo_nome,observacoes,socios(numero_socio,nome,email,telemovel),acoes(titulo,data,hora,local,valor,pagamento_obrigatorio)').eq('acao_id',id).order('data_inscricao',{ascending:false});const r=await q;if(r.error)throw r.error;return r.data||[]}
async function listRegs(id){const el=$(`regs-${id}`);if(!el)return;if(!el.hidden){el.hidden=true;return}el.hidden=false;el.innerHTML='A carregar…';try{const rows=await regs(id);el.innerHTML=rows.length?`<table class="acao-inscricoes-table"><thead><tr><th>Nº</th><th>Sócio</th><th>Inscrito</th><th>Pagamento</th><th>Comprovativo</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.socios?.numero_socio)}</td><td><strong>${esc(r.socios?.nome)}</strong><br>${esc(r.socios?.email||'')}</td><td>${dt(r.data_inscricao)}</td><td>${r.acoes?.pagamento_obrigatorio?(r.pagamento_confirmado?'✅ Confirmado':'⏳ Pendente'):'Sem pagamento'}</td><td>${r.comprovativo_path?`<button class="admin-small-btn" data-proof="${r.id}">Abrir</button>`:'—'}</td><td><select data-state="${r.id}">${['pendente','confirmada','cancelada','rejeitada'].map(s=>`<option ${r.estado===s?'selected':''}>${s}</option>`).join('')}</select></td><td>${r.acoes?.pagamento_obrigatorio&&!r.pagamento_confirmado?`<button class="admin-small-btn primary" data-pay="${r.id}">Confirmar pagamento</button>`:''}</td></tr>`).join('')}</tbody></table>`:'<div class="acao-empty">Sem inscrições.</div>';bindRegButtons(el)}catch(e){el.textContent=e.message}}
function bindRegButtons(root){root.querySelectorAll('[data-proof]').forEach(b=>b.onclick=async()=>{try{const r=await sb.from('acoes_inscricoes').select('comprovativo_path').eq('id',b.dataset.proof).single();if(r.error)throw r.error;const u=await sb.storage.from('comprovativos-acoes').createSignedUrl(r.data.comprovativo_path,300);if(u.error)throw u.error;window.open(u.data.signedUrl,'_blank','noopener')}catch(e){result(e.message,'error')}});root.querySelectorAll('[data-state]').forEach(s=>s.onchange=async()=>{const r=await sb.from('acoes_inscricoes').update({estado:s.value}).eq('id',s.dataset.state);if(r.error)result(r.error.message,'error');else result('Estado atualizado.')});root.querySelectorAll('[data-pay]').forEach(b=>b.onclick=async()=>{const r=await sb.from('acoes_inscricoes').update({pagamento_confirmado:true,estado:'confirmada'}).eq('id',b.dataset.pay);if(r.error)result(r.error.message,'error');else result('Pagamento confirmado.');})}
async function exportRegs(actionId){try{const XLSX=await xlsx();let q=sb.from('acoes_inscricoes').select('id,data_inscricao,estado,pagamento_confirmado,comprovativo_nome,observacoes,socios(numero_socio,nome,email,telemovel),acoes(titulo,data,hora,local,valor,pagamento_obrigatorio)');if(actionId)q=q.eq('acao_id',actionId);const r=await q;if(r.error)throw r.error;if(!r.data?.length)throw Error('Não existem inscrições para exportar.');const rows=r.data.map(x=>({'Nº Sócio':x.socios?.numero_socio||'','Nome':x.socios?.nome||'','Email':x.socios?.email||'','Telemóvel':x.socios?.telemovel||'','Atividade':x.acoes?.titulo||'','Data':x.acoes?.data||'','Hora':x.acoes?.hora?String(x.acoes.hora).slice(0,5):'','Local':x.acoes?.local||'','Inscrito em':dt(x.data_inscricao),'Valor':x.acoes?.pagamento_obrigatorio?Number(x.acoes?.valor||0):0,'Pagamento confirmado':x.pagamento_confirmado?'Sim':'Não','Comprovativo':x.comprovativo_nome||'','Estado':x.estado||'','Observações':x.observacoes||''}));const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=Object.keys(rows[0]).map(k=>({wch:Math.min(38,Math.max(14,k.length+3))}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Inscrições');XLSX.writeFile(wb,`inscricoes-acoes-${new Date().toISOString().slice(0,10)}.xlsx`);result('Excel exportado.')}catch(e){result(e.message||String(e),'error')}}
async function init(){const root=$('acoes-admin-module');if(!root||!window.__NAF_SUPABASE)return;sb=window.__NAF_SUPABASE;try{const r=await sb.rpc('is_admin');if(r.error||r.data!==true){root.hidden=true;return}root.hidden=false;$('acoes-admin-form-wrap').innerHTML=form();bindForm();$('acoes-refresh').onclick=()=>load().catch(e=>result(e.message,'error'));$('acoes-export-all').onclick=()=>exportRegs();await load()}catch(e){result(e.message,'error')}}
document.addEventListener('DOMContentLoaded',init);
})();
