-- Reconstrução funcional NAF Marques Bom
-- Executar no Supabase SQL Editor antes de publicar o frontend.

-- 1) Dados usados publicamente na área "Sócio".
ALTER TABLE public.socios ADD COLUMN IF NOT EXISTS modalidade text;
ALTER TABLE public.socios ADD COLUMN IF NOT EXISTS categoria text;
ALTER TABLE public.socios ADD COLUMN IF NOT EXISTS data_nascimento date;

CREATE OR REPLACE FUNCTION public.socios_publicos_por_categoria()
RETURNS TABLE(nome text, modalidade text, categoria text)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT s.nome, s.modalidade, s.categoria
  FROM public.socios s
  WHERE s.ativo = true
    AND s.nome IS NOT NULL
    AND trim(s.nome) <> ''
    AND s.categoria IS NOT NULL
    AND trim(s.categoria) <> ''
    AND lower(coalesce(s.modalidade,'')) IN ('futebol','futsal')
  ORDER BY lower(s.modalidade), lower(s.categoria), lower(s.nome);
$$;
REVOKE ALL ON FUNCTION public.socios_publicos_por_categoria() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.socios_publicos_por_categoria() TO anon, authenticated;

-- 2) Quotas Excel: garantir valor e unicidade.
ALTER TABLE public.quotas ADD COLUMN IF NOT EXISTS valor numeric(10,2);
CREATE UNIQUE INDEX IF NOT EXISTS quotas_socio_ano_mes_uq ON public.quotas(socio_id,ano,mes);

-- 3) Alteração segura do número de sócio pelo administrador.
CREATE OR REPLACE FUNCTION public.admin_alterar_numero_socio(p_socio_id uuid, p_numero integer)
RETURNS public.socios
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  caller public.socios;
  target public.socios;
  result public.socios;
BEGIN
  SELECT * INTO caller FROM public.socios
  WHERE user_id = auth.uid() AND ativo = true LIMIT 1;

  IF caller.id IS NULL OR caller.is_admin IS DISTINCT FROM true OR caller.numero_socio <> 9999 THEN
    RAISE EXCEPTION 'Acesso reservado ao administrador.';
  END IF;
  IF p_numero IS NULL OR p_numero <= 0 OR p_numero = 9999 THEN
    RAISE EXCEPTION 'Número de sócio inválido.';
  END IF;

  SELECT * INTO target FROM public.socios WHERE id = p_socio_id FOR UPDATE;
  IF target.id IS NULL THEN RAISE EXCEPTION 'Sócio não encontrado.'; END IF;

  IF EXISTS (SELECT 1 FROM public.socios WHERE numero_socio = p_numero AND id <> p_socio_id) THEN
    RAISE EXCEPTION 'O número de sócio % já existe.', p_numero;
  END IF;

  UPDATE public.socios SET numero_socio = p_numero WHERE id = p_socio_id RETURNING * INTO result;
  RETURN result;
END;
$$;
REVOKE ALL ON FUNCTION public.admin_alterar_numero_socio(uuid,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_alterar_numero_socio(uuid,integer) TO authenticated;

-- 4) Registo anti-duplicação dos emails de aniversário.
CREATE TABLE IF NOT EXISTS public.emails_aniversario (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  socio_id uuid NOT NULL REFERENCES public.socios(id) ON DELETE CASCADE,
  ano integer NOT NULL,
  enviado_em timestamptz NOT NULL DEFAULT now(),
  UNIQUE(socio_id, ano)
);
ALTER TABLE public.emails_aniversario ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.emails_aniversario FROM PUBLIC;
